transman/auth/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^home$', views.home, name='home'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
]

transman/transman/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from auth import views

urlpatterns = [
    url(r'^$', views.home),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/', include('auth.urls')),
    url(r'^work/', include('work.urls')),
]

transman/work/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list$', views.list, name='list'),
    url(r'^listout$', views.listout, name='listout'),
    url(r'^detail$', views.detail, name='detail'),
    url(r'^new$', views.new, name='new'),
    url(r'^arrive$', views.arrive, name='arrive'),
    url(r'^scan$', views.scan, name='scan'),
    url(r'^selectCard$', views.selectCard, name='selectCard'),
    url(r'^pay$', views.pay, name='pay'),
    url(r'^payout$', views.payout, name='payout'),
    url(r'^out$', views.out, name='out'),
    url(r'^outdetail$', views.outdetail, name='outdetail'),
    url(r'^balance$', views.balance, name='balance'),
]

transman/work/forms.py
#coding:utf-8
from django import forms
from .models import TransRec,Card,OutRec
from django.contrib.auth.models import User,Permission

class ScanForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super(ScanForm,self).__init__(*args,**kwargs)
        self.fields['qrcode'].widget.attrs.update({'autofocus': 'true'})
    qrcode=forms.CharField(label=("二维码"),required=True)

class NewForm(forms.ModelForm):
    def __init__(self,mine_queryset,*args,**kwargs):
        super(NewForm,self).__init__(*args,**kwargs)
        self.fields['mine'].queryset=mine_queryset
    class Meta:
        model=TransRec
        fields=[
            'car_no',
            'driver_name',
            'contact_info',
            'mine',
            'coal_type',
            'scale',
            'unit',
        ]
        labels={
            'car_no':'车牌号',
            'driver_name':'驾驶员姓名',
            'contact_info':'联系方式',
            'mine':'出发煤矿',
            'coal_type':'煤类型',
            'scale':'目标磅房',
            'unit':'单价',
        }

class OutForm(forms.ModelForm):
    class Meta:
        model=OutRec
        fields=[
            'car_no',
            'driver_name',
            'contact_info',
            'amount',
            'unit',
            'qrcode'
        ]
        labels={
            'car_no':'车牌号',
            'driver_name':'驾驶员姓名',
            'contact_info':'联系方式',
            'amount':'出货量',
            'unit':'单价',
            'qrcode':'二维码'
        }

class ArriveForm(forms.ModelForm):
    def __init__(self,qrcode,*args,**kwargs):
        super(ArriveForm,self).__init__(*args,**kwargs)
        self.fields['qrcode']=forms.CharField(widget=forms.HiddenInput(),initial=qrcode)
    class Meta:
        model=TransRec
        fields=[
            'setoff_amount',
            'arrive_amount',
        ]
        labels={
            'setoff_amount':'矿发量',
            'arrive_amount':'实收量'
        }

class SelectCardForm(forms.Form):
    qrcode=forms.CharField(widget=forms.HiddenInput())
    card=forms.ModelChoiceField(label=('油卡'),queryset=Card.objects.all())

class PayForm(forms.Form):
    qrcode=forms.CharField(widget=forms.HiddenInput())
    payfor=forms.CharField(widget=forms.HiddenInput())

class SearchForm(forms.Form):
    def __init__(self,*args,**kwargs):
        super(SearchForm,self).__init__(*args,**kwargs)
        perm_scale=Permission.objects.get(codename='scale')
        opscales=User.objects.filter(user_permissions=perm_scale)
        perm_account=Permission.objects.get(codename='account')
        opaccounts=User.objects.filter(user_permissions=perm_account)
        self.fields['opscale']=forms.ModelChoiceField(label='磅房操作员',queryset=opscales)
        self.fields['opaccount']=forms.ModelChoiceField(label='财务操作员',queryset=opaccounts)
    setoff_time_begin=forms.DateField(label='出发时间从',widget=forms.TextInput(attrs={'class':'datepicker'}))
    setoff_time_end=forms.DateField(label='至',widget=forms.TextInput(attrs={'class':'datepicker'}))
    arrive_time_begin=forms.DateField(label='到磅时间从',widget=forms.TextInput(attrs={'class':'datepicker'}))
    arrive_time_end=forms.DateField(label='至',widget=forms.TextInput(attrs={'class':'datepicker'}))
    car_no=forms.CharField(label='车牌号',max_length=10)

class SearchOutForm(forms.Form):
    setoff_time_begin=forms.DateField(label='出发时间从',widget=forms.TextInput(attrs={'class':'datepicker'}))
    setoff_time_end=forms.DateField(label='至',widget=forms.TextInput(attrs={'class':'datepicker'}))
    car_no=forms.CharField(label='车牌号',max_length=10)

transman/work/views.py
#coding:utf-8
from django.shortcuts import render,redirect
from .models import TransRec,Mine,Balance,Card,OutRec,CoalType,Scale
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
import random,string,datetime
from django.contrib.auth.decorators import permission_required,login_required
from django.core.exceptions import ObjectDoesNotExist,PermissionDenied
from .forms import ScanForm,NewForm,ArriveForm,SelectCardForm,PayForm,OutForm,SearchForm,SearchOutForm
from django.db.models import Sum,F
from django.http import HttpResponse
import xlwt

def randqr():
    qrcode=''.join([random.choice(string.digits+string.lowercase) for i in range(10)])
    while TransRec.objects.filter(qrcode=qrcode).exists() or OutRec.objects.filter(qrcode=qrcode).exists():
        qrcode=''.join([random.choice(string.digits+string.lowercase) for i in range(10)])
    return qrcode

# Create your views here.
@login_required
def list(request):
    all_recs=TransRec.objects
    user=request.user
    if user.has_perm('work.mine'):
        all_recs=all_recs.filter(mine__user=user)
        perm='mine'
    elif user.has_perm('work.scale'):
        all_recs=all_recs.filter(scale=user.userscaleinfo.scale)
        perm='scale'
    elif user.has_perm('work.account'):
        perm='account'
    else:
        raise PermissionDenied

    setoff_time_begin=request.GET.get('setoff_time_begin')
    setoff_time_end=request.GET.get('setoff_time_end')
    arrive_time_begin=request.GET.get('arrive_time_begin')
    arrive_time_end=request.GET.get('arrive_time_end')
    car_no=request.GET.get('car_no')
    opscale=request.GET.get('opscale')
    opaccount=request.GET.get('opaccount')
    if setoff_time_begin:
        all_recs=all_recs.filter(setoff_time__gt=setoff_time_begin)
    if setoff_time_end:
        setoff_time_end+=' 23:59:59'
        all_recs=all_recs.filter(setoff_time__lt=setoff_time_end)
    if arrive_time_begin:
        all_recs=all_recs.filter(arrive_time__gt=arrive_time_begin)
    if arrive_time_end:
        arrive_time_end+=' 23:59:59'
        all_recs=all_recs.filter(arrive_time__lt=arrive_time_end)
    if car_no:
        all_recs=all_recs.filter(car_no=car_no)
    if opscale:
        all_recs=all_recs.filter(opscale=opscale)
    if opaccount:
        all_recs=all_recs.filter(opaccount=opaccount)


    download=request.GET.get('download')
    if download:
        xls=xlwt.Workbook(encoding='utf8',style_compression={})
        sheet=xls.add_sheet('Sheet1')
        style=xlwt.easyxf('align: horiz right')
        labels=['ID','车牌号','驾驶员姓名','联系方式','出发煤矿','煤类型','到达磅房','出发时间','矿发量','实收量','单价','到达时间','总价']
        for i in range(len(labels)):
            sheet.write(0,i,labels[i],style=style)
        row=1
        sum=0.0
        for rec in all_recs.all():
            sheet.write(row,0,rec.id,style=style)
            sheet.write(row,1,rec.car_no,style=style)
            sheet.write(row,2,rec.driver_name,style=style)
            sheet.write(row,3,rec.contact_info,style=style)
            sheet.write(row,4,rec.mine.name,style=style)
            sheet.write(row,5,rec.coal_type.name,style=style)
            sheet.write(row,6,rec.scale.name,style=style)
            sheet.write(row,7,rec.setoff_time.strftime('%Y-%m-%d %H:%M:%S'),style=style)
            setoff_amount=rec.setoff_amount if rec.setoff_amount else '---'
            sheet.write(row,8,setoff_amount,style=style)
            arrive_amount=rec.arrive_amount if rec.arrive_amount else '---'
            sheet.write(row,9,arrive_amount,style=style)
            sheet.write(row,10,rec.unit,style=style)
            arrive_time=rec.arrive_time.strftime('%Y-%m-%d %H:%M:%S') if rec.arrive_time else '-----'
            sheet.write(row,11,arrive_time,style=style)
            if rec.arrive_amount:
                total=(rec.unit*rec.arrive_amount)//10*10
                sum+=total
            else:
                total='---'
            sheet.write(row,12,total,style=style)
            row+=1
        sheet.write(row,0,'合计',style=style)
        sheet.write(row,12,sum,style=style)
        response = HttpResponse(content_type='application/vnd.ms-excel')
        response['Content-Disposition'] = 'attachment; filename=list.xls'
        xls.save(response)
        return response

    params=''
    for k,v in request.GET.items():
        if k!='page':
            params+=k+'='+v+'&'

    all_recs=all_recs.order_by('-id')

    paginator=Paginator(all_recs,10)
    page=request.GET.get('page')
    try:
        recs=paginator.page(page)
    except PageNotAnInteger:
        recs=paginator.page(1)
    except EmptyPage:
        recs=paginator.page(paginator.num_pages)
    begin=recs.number-5/2
    if begin<1:begin=1
    end=recs.number+5/2
    if end>paginator.num_pages:end=paginator.num_pages
    pr=range(begin,end+1)
    
    form=SearchForm()
    return render(request,'work/list.html',{'recs':recs,'perm':perm,'pr':pr,'params':params,'form':form})

def listout(request):
    all_recs=OutRec.objects
    user=request.user
    if user.has_perm('work.scale'):
        perm='scale'
        all_recs=all_recs.filter(scale=request.user.userscaleinfo.scale)
    elif user.has_perm('work.account'):
        perm='account'
    else:
        raise PermissionDenied

    payed=None
    sum=None
    qrcode=request.GET.get('qrcode')
    if qrcode:
        all_recs=all_recs.filter(qrcode=qrcode)
        if not all_recs.exists():
            return render(request,'work/info.html',{'title':'错误','content':'无法识别此二维码'})
        if all_recs[0].payed:
            payed=True
        else:
            payed=False
            sum=0.0
            for rec in all_recs:
                sum+=rec.unit*rec.amount
            sum=sum//10*10

    setoff_time_begin=request.GET.get('setoff_time_begin')
    setoff_time_end=request.GET.get('setoff_time_end')
    car_no=request.GET.get('car_no')
    if setoff_time_begin:
        all_recs=all_recs.filter(setoff_time__gt=setoff_time_begin)
    if setoff_time_end:
        setoff_time_end+=' 23:59:59'
        all_recs=all_recs.filter(setoff_time__lt=setoff_time_end)
    if car_no:
        all_recs=all_recs.filter(car_no=car_no)

    all_recs=all_recs.order_by('-id')

    params=''
    for k,v in request.GET.items():
        if k!='page':
            params+=k+'='+v+'&'

    paginator=Paginator(all_recs,10)
    page=request.GET.get('page')
    try:
        recs=paginator.page(page)
    except PageNotAnInteger:
        recs=paginator.page(1)
    except EmptyPage:
        recs=paginator.page(paginator.num_pages)
    begin=recs.number-5/2
    if begin<1:begin=1
    end=recs.number+5/2
    if end>paginator.num_pages:end=paginator.num_pages
    pr=range(begin,end+1)

    form=SearchOutForm()
    return render(request,'work/listout.html',{'recs':recs,'qrcode':qrcode,'perm':perm,'payed':payed,'pr':pr,'sum':sum,'params':params,'form':form})

@permission_required('work.mine',raise_exception=True)
def new(request):
    user=request.user
    if request.method=='POST':
        form=NewForm(Mine.objects.filter(user=user),request.POST)
        if form.is_valid():
            rec=form.save(commit=False)
            rec.qrcode=randqr()
            rec.save()
            return redirect('/work/detail?qrcode='+str(rec.qrcode))
    form=NewForm(Mine.objects.filter(user=user))
    return render(request,'work/new.html',{'form':form})

@permission_required('work.scale',raise_exception=True)
def out(request):
    if request.method=='POST':
        form=OutForm(request.POST)
        if form.is_valid():
            qrcode=form.cleaned_data['qrcode']
            if qrcode:
                recs=OutRec.objects.filter(scale=request.user.userscaleinfo.scale,qrcode=qrcode)
                if recs.exists():
                    rec=recs[0]
                    if rec.payed:
                        return render(request,'work/info.html',{'title':'错误','content':'二维码已作废'})
                    rec.pk=None
                    rec.amount=form.cleaned_data['amount']
                    rec.unit=form.cleaned_data['unit']
                    rec.save()
                    return redirect('/work/listout?qrcode='+rec.qrcode)
                else:
                    return render(request,'work/info.html',{'title':'错误','content':'无法识别此二维码'})
            else:
                rec=form.save(commit=False)
                rec.scale=request.user.userscaleinfo.scale
                rec.qrcode=randqr()
                rec.save()
                return redirect('/work/outdetail?id='+str(rec.id))
        else:
            return render(request,'work/info.html',{'title':'错误','content':'表格填写错误'})
    form=OutForm()
    return render(request,'work/out.html',{
        'form':form
    })

@login_required
def detail(request):
    qrcode=request.GET.get('qrcode')
    try:
        rec=TransRec.objects.get(qrcode=qrcode)
    except ObjectDoesNotExist:
        return render(request,'work/info.html',{'title':'错误','content':'无法识别此二维码'})
    return render(request,'work/detail.html',{'rec':rec})

@permission_required('work.scale',raise_exception=True)
def outdetail(request):
    id=request.GET.get('id')
    try:
        rec=OutRec.objects.get(id=id)
    except ObjectDoesNotExist:
        return render(request,'work/info.html',{'title':'错误','content':'无此id'})
    return render(request,'work/outdetail.html',{'rec':rec})

@permission_required('work.account',raise_exception=True)
def payout(request):
    qrcode=request.GET.get('qrcode')
    recs=OutRec.objects.filter(qrcode=qrcode)
    if recs.exists():
        sum=0.0
        for rec in recs:
            if rec.payed:
                continue
            sum+=rec.unit*rec.amount
            rec.payed=True
            rec.save()
        sum=sum//10*10
        balance=Balance.objects.get(pk=1)
        balance.balance-=sum
        balance.save()
        return render(request,'work/info.html',{'title':'成功','content':'付款成功'})
    else:
        return render(request,'work/info.html',{'title':'错误','content':'无法识别此二维码'})

transman/templates/work/arrive.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>到货称重</title>

        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/style.css" rel="stylesheet">
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <h1>
                        详细信息
                    </h1>
                    <div class="list-group text-center">
                        <div class="list-group-item">
                            车牌号：
                            {{rec.car_no}}
                        </div>
                        <div class="list-group-item">
                            驾驶员姓名：
                            {{rec.driver_name}}
                        </div>
                        <div class="list-group-item">
                            联系方式：
                            {{rec.contact_info}}
                        </div>
                        <div class="list-group-item">
                            发货煤矿：
                            {{rec.mine.name}}
                        </div>
                        <div class="list-group-item">
                            煤类型：
                            {{rec.coal_type.name}}
                        </div>
                        <div class="list-group-item">
                            目标磅房：
                            {{rec.scale.name}}
                        </div>
                        <div class="list-group-item">
                            单价：
                            {{rec.unit}}
                        </div>
                    </div>
                    {% if not rec.arrive_amount %}
                    <h1>请填写重量</h1>
                    <form role="form" action="/work/arrive" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="buttons">
                            <button type="submit" class="btn btn-primary btn-lg">
                                确定
                            </button>
                            <a role="button" href="list" class="btn btn-primary btn-lg">
                                返回
                            </a>
                        </div>
                    </form>
                    {% else %}
                    <div class="buttons">
                        <a role="button" href="list" class="btn btn-primary btn-lg">
                            返回列表
                        </a>
                    </div>
                    {% endif %}
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <br>
        </div>

        <script src="/static/jquery.min.js"></script>
        <script src="/static/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/script.js"></script>
    </body>
</html>

transman/templates/work/balance.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>统计信息</title>

        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/style.css" rel="stylesheet">

    </head>
    <body>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-1">
                </div>
                <div class="col-md-10">
                    <h1>
                        统计信息
                    </h1>

                    <h2>
                        矿厂出货信息：
                    </h2>
                    <div class="container">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        矿厂名
                                    </th>
                                    {% for coal_type in coal_types %}
                                    <th>
                                        {{ coal_type.name }}
                                    </th>
                                    {% endfor %}
                                    <th>
                                        合计
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in mine_table %}
                                <tr>
                                    {% for v in row %}
                                    <td>
                                        {{ v }}
                                    </td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td>
                                        合计
                                    </td>
                                    {% for coal_type in coal_types %}
                                    <td>
                                    </td>
                                    {% endfor %}
                                    <td>
                                        {{ mine_total }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <h2>
                        磅房进出货信息：
                    </h2>
                    <div class="container">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        磅房名
                                    </th>
                                    {% for coal_type in coal_types %}
                                    <th>
                                        {{ coal_type.name }}
                                    </th>
                                    {% endfor %}
                                    <th>
                                        进货合计
                                    </th>
                                    <th>
                                        出货量
                                    </th>
                                    <th>
                                        余量
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for row in scale_table %}
                                <tr>
                                    {% for v in row %}
                                    <td>
                                        {{ v }}
                                    </td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                                <tr>
                                    <td>
                                        合计
                                    </td>
                                    {% for coal_type in coal_types %}
                                    <td>
                                    </td>
                                    {% endfor %}
                                    <td>
                                        {{ in_total }}
                                    </td>
                                    <td>
                                        {{ out_total }}
                                    </td>
                                    <td>
                                        {{ balance_total }}
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <h2>
                        运费信息：
                    </h2>
                    <div class="container">
                        <table class="table">
                            <thead>
                                <tr>
                                <th>
                                    进货总运费
                                </th>
                                <th>
                                    出货总运费
                                </th>
                                <th>
                                    现金余额
                                </th>
                                <tr>
                            </thead>
                            <tbody>
                                <tr>
                                    {% for v in cash_info %}
                                    <td>
                                        {{ v }}
                                    </td>
                                    {% endfor %}
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <h2>
                        油卡信息：
                    </h2>
                    <div class="container">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        面额（元）
                                    </th>
                                    <th>
                                        已付数量（张）
                                    </th>
                                    <th>
                                        余量（张）
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for card_info in cards_info %}
                                <tr>
                                    {% for v in card_info %}
                                    <td>
                                        {{ v }}
                                    </td>
                                    {% endfor %}
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    <div class="buttons">
                        <a role="button" href="/work/list" class="btn btn-primary btn-lg">
                            返回列表
                        </a>
                    </div>
                </div>
                <div class="col-md-1">
                </div>
            </div>
            <br>
        </div>
        <script src="/static/jquery.min.js"></script>
        <script src="/static/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/script.js"></script>
    </body>
</html>

transman/templates/work/pay.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>付款</title>

        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/style.css" rel="stylesheet">

    </head>
    <body>

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <h1 class="text-center">
                        详细信息
                    </h1>
                    <div class="list-group text-center">
                        <div class="list-group-item">
                            车牌号：
                            {{rec.car_no}}
                        </div>
                        <div class="list-group-item">
                            驾驶员姓名：
                            {{rec.driver_name}}
                        </div>
                        <div class="list-group-item">
                            联系方式：
                            {{rec.contact_info}}
                        </div>
                        <div class="list-group-item">
                            发货煤矿：
                            {{rec.mine.name}}
                        </div>
                        <div class="list-group-item">
                            煤类型：
                            {{rec.coal_type.name}}
                        </div>
                        <div class="list-group-item">
                            目标磅房：
                            {{rec.scale.name}}
                        </div>
                        <div class="list-group-item">
                            出发时间：
                            {{ rec.setoff_time|date:"Y-m-d H:i:s" }}
                        </div>
                        <div class="list-group-item">
                            矿发量：
                            {{ rec.setoff_amount }}
                        </div>
                        <div class="list-group-item">
                            实收量：
                            {{ rec.arrive_amount }}
                        </div>
                        <div class="list-group-item">
                            到达时间：
                            {{ rec.arrive_time|date:"Y-m-d H:i:s" }}
                        </div>
                        <div class="list-group-item">
                            总运费：
                            {{ total }}
                        </div>
                        <div class="list-group-item">
                            应付油卡：
                            {{ rec.card.value }}
                        </div>
                        <div class="list-group-item">
                            油卡已付：
                            {% autoescape off %}
                            {{ rec.card_payed|yesno:"<font color='blue'>是</font>,<font color='red'>否</font>" }}
                            {% endautoescape %}
                        </div>
                        <div class="list-group-item">
                            应付现金：
                            {{ rec.cash }}
                        </div>
                        <div class="list-group-item">
                            现金已付：
                            {% autoescape off %}
                            {{ rec.cash_payed|yesno:"<font color='blue'>是</font>,<font color='red'>否</font>" }}
                            {% endautoescape %}
                        </div>
                    </div>
                    <form role="form" id="form" action="/work/pay" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="buttons">
                            {% if not rec.card_payed %}
                            <button type="button" class="btn btn-primary btn-lg" onclick="$('#id_payfor').val('card');$('#form').submit()">
                                付油卡
                            </button>
                            {% endif %}
                            {% if not rec.cash_payed %}
                            <button type="button" class="btn btn-primary btn-lg" onclick="$('#id_payfor').val('cash');$('#form').submit()">
                                付现金
                            </button>
                            {% endif %}
                            {% if not rec.card_payed and not rec.cash_payed %}
                            <button type="button" class="btn btn-primary btn-lg" onclick="$('#id_payfor').val('both');$('#form').submit()">
                                付油卡和现金
                            </button>
                            {% endif %}
                            <a role="button" href="list" class="btn btn-primary btn-lg">
                                返回列表
                            </a>
                        </div>
                    </form>
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <br>
        </div>

        <script src="/static/jquery.min.js"></script>
        <script src="/static/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/script.js"></script>
    </body>
</html>